#!/usr/bin/env python3
"""
N=100 query generation for the scale-up eval (Phase C prep).

CRITICAL anti-confound: this script is a pure templated generator - no LLM of
any kind (in the model panel or otherwise) is called at any point. Query text
is produced by filling node labels from the two existing, frozen seed graphs
(poc_compare.DEMO_GRAPH, seed_graph_2.DEMO_GRAPH_2 - imported, not copied,
not modified) into a fixed bank of question templates written by hand before
this script ran. This keeps generation fully deterministic and auditable:
running this script twice produces byte-identical output.

Query TYPE is constrained to match the original 12 PRIORITY_QUERIES exactly:
every query asks for a single decisive pick (open-ended "what's my priority"
or forced-choice "between A and B / among A, B, C, which"), never a
descriptive/attribute question ("how urgent is X"). This is deliberate - the
frozen v2 COMMIT/HEDGE scorer and the correctness extractor are both built
around "does the response commit to one specific named answer," and mixing
in attribute-style questions would repeat the exact v1 DESCRIPTIVE/PRIORITY
scorer-category-mismatch bug documented in poc_compare_v2.py's docstring.

Three query families, all decisive-pick:
  GENERIC   - context-free, no node names (20 queries, same flavor as the
              original 10 reused-verbatim generics + 10 new phrasings; one
              is the original "What's holding me back..." blocker query,
              carried forward with the same ambiguous/N-A ground truth
              treatment established for the original 12).
  PAIRWISE  - "Between A and B, which should I prioritize?" and 3 phrasing
              variants, filled with domain/theme label pairs from each
              graph's own seed weights, enumerated in a fixed deterministic
              order (itertools.combinations), no randomness.
  TRIPLE    - "Among A, B, and C, which should take priority?", filled with
              domain/theme label triples, same deterministic enumeration.

Ground truth:
  GENERIC   -> top_path (identical convention to the existing 12: any node
               on the single highest-weight root-to-leaf path is CORRECT).
  PAIRWISE  -> the higher-weighted of the two named nodes is CORRECT.
               Near-ties (|weight_a - weight_b| < NEAR_TIE_THRESHOLD) are
               flagged and EXCLUDED from the correctness metric - the
               ground truth itself is too close to trust as a boundary.
  TRIPLE    -> the highest-weighted of the three. Near-tie exclusion applies
               to the gap between the top two (the pair that actually
               decides "correct").

NEAR_TIE_THRESHOLD = 3.5 weight points - the chain weight formula's own
decay step (base_weight * 0.05 per position), which for the theme weights
actually in use (~50-85) works out to roughly 2.5-4.25 points; 3.5 is the
representative figure. A margin below this is indistinguishable from the
graph's own generation noise, not a real ground-truth signal.

IMPORTANT (fixed after an initial version of this script silently used the
wrong comparison): the margin computed here is a REAL per-query comparison
against the query's own relevant competitor, not a fixed global figure -
  PAIRWISE  -> |weight(A) - weight(B)|, the two nodes actually named in
               that query.
  TRIPLE    -> weight(top-ranked of the three) - weight(second-ranked of
               the three), the two nodes that actually decide "correct"
               for that query.
  GENERIC   -> min(weight of every node on the top_path) - max(weight of
               every node NOT on the top_path), across ALL nodes in the
               graph (domain, theme, AND concept level - a generic "what's
               my priority" question is not scoped to any sub-region, so
               its true competitor can be any node anywhere). This is the
               most conservative possible margin: it asks whether even the
               WEAKEST link of the top path still beats the STRONGEST
               competitor outside it, at any granularity a response might
               name. An earlier version of this script hardcoded
               near_tie=False for the entire generic family without ever
               computing this - a real bug, found and fixed before any
               live call, not after seeing scored data.

Usage: python research/generate_queries_n100.py
Outputs (research/, frozen - not regenerated by any other script):
  queries_n100_graph1.json
  queries_n100_graph2.json
Each entry: {id, text, family, ground_truth: {mode, correct, wrong, near_tie}}
"""
import itertools
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from poc_compare import DEMO_GRAPH, DEMO_USER
from seed_graph_2 import DEMO_GRAPH_2, DEMO_USER_2
from correctness_analysis import TOP_PATH_LABELS
from correctness_analysis_graph2 import TOP_PATH_LABELS_2

NEAR_TIE_THRESHOLD = 3.5

# ============================================================
# GENERIC family - 20 queries, graph-agnostic (same text used for both
# graphs, same convention as the original 12's 10 reused-verbatim generics).
# Query #7 is the carried-forward blocker query, ambiguous ground truth.
# ============================================================
GENERIC_QUERIES = [
    "What's my top priority right now?",
    "What should I focus on next?",
    "If I could only work on one thing this week, what should it be?",
    "What's the single most important thing I should be doing today?",
    "Rank my current projects from most to least urgent.",
    "I only have a few free hours this weekend - what should I spend them on?",
    "What's holding me back the most right now?",  # ambiguous, excluded from correctness
    "Which of my interests deserves the most attention this month?",
    "What's the one thing that, if I finished it, would unlock the most progress?",
    "What's the highest-leverage use of my time this week?",
    "If you had to pick just one thing for me to work on tomorrow, what would it be?",
    "What deserves my full attention this week?",
    "Out of everything on my plate, what matters most right now?",
    "What should be at the top of my to-do list today?",
    "If I had to drop everything else and focus on one thing, what should it be?",
    "What's the smartest use of my next free hour?",
    "Which of my current efforts is most urgent?",
    "What should I prioritize above everything else this month?",
    "If someone asked what I'm most focused on right now, what should the honest answer be?",
    "What's the one project I shouldn't let slip this week?",
]
BLOCKER_QUERY = "What's holding me back the most right now?"

PAIRWISE_TEMPLATES = [
    "Between {a} and {b}, which should I prioritize?",
    "Should I focus on {a} or {b} first?",
    "If I had to choose between {a} and {b} this week, which comes first?",
    "{a} or {b} - which one deserves my attention right now?",
]
TRIPLE_TEMPLATES = [
    "Among {a}, {b}, and {c}, which should take priority?",
    "Of {a}, {b}, and {c}, which one comes first?",
]


def _pool(graph_data):
    """(label, weight) for every domain and theme - the two levels a forced-
    choice question can plausibly name as a coherent 'thing to prioritize'.
    Concept-level chain items are deliberately excluded from this pool: they
    read as sub-steps of a theme, not standalone priorities, and using them
    would produce awkward/unnatural forced-choice phrasing."""
    pool = []
    for d in graph_data:
        pool.append((d["domain"], float(d["domain_weight"])))
        for t in d["themes"]:
            pool.append((t["name"], float(t["weight"])))
    return pool


def _all_node_weights(graph_data) -> dict:
    """label -> weight for EVERY node (domain, theme, AND concept/chain level),
    same weight formula _seed_demo_graph[_2] uses. Needed for GENERIC-query
    margins specifically: a 'what's my priority' question isn't scoped to the
    domain/theme pool the way a forced-choice question is, so its true
    competitor could be a concept-level node (e.g. a different theme's own
    top chain item, which shares that theme's exact weight at position 0)."""
    weights = {}
    for d in graph_data:
        weights[d["domain"]] = float(d["domain_weight"])
        for t in d["themes"]:
            weights[t["name"]] = float(t["weight"])
            base = t["weight"]
            for i, title in enumerate(t["chain"]):
                weights[title] = round(base * (1 - 0.05 * i), 1)
    return weights


def _ancestor_pairs(graph_data) -> set:
    """(domain, theme) label pairs that are in a parent-child relationship -
    excluded from forced-choice generation. 'Between Open Source Development
    and AI Memory Tools, which should I prioritize?' is not a coherent
    question when AI Memory Tools is a theme INSIDE Open Source Development;
    it's asking to choose between a category and its own subset. Found via
    inspection of the first generated batch, fixed before this ever reached
    a live call."""
    pairs = set()
    for d in graph_data:
        for t in d["themes"]:
            pairs.add(frozenset((d["domain"], t["name"])))
    return pairs


def _generic_margin(graph_data, top_path_labels) -> float:
    all_weights = _all_node_weights(graph_data)
    top_path_weights = [w for lbl, w in all_weights.items() if lbl in top_path_labels]
    non_top_path_weights = [w for lbl, w in all_weights.items() if lbl not in top_path_labels]
    return min(top_path_weights) - max(non_top_path_weights)


def _generic_entries(graph_data, top_path_labels):
    margin = round(_generic_margin(graph_data, top_path_labels), 1)
    entries = []
    for i, q in enumerate(GENERIC_QUERIES, 1):
        if q == BLOCKER_QUERY:
            gt = {"mode": "ambiguous", "correct": None, "wrong": None, "near_tie": False}
        else:
            gt = {"mode": "top_path", "correct": list(top_path_labels), "wrong": None,
                  "near_tie": margin < NEAR_TIE_THRESHOLD, "gap": margin}
        entries.append({"id": f"generic_{i}", "text": q, "family": "generic", "ground_truth": gt})
    return entries


def _pairwise_entries(pool, ancestor_pairs, target_count):
    """Each distinct (non-ancestor) label pair is used AT MOST ONCE - if
    target_count exceeds the number of distinct valid pairs available (true
    for graph1's smaller 10-label pool: only 39 valid pairs exist), this
    returns fewer than target_count rather than padding out with repeated
    label-pairs under different phrasing, which would inflate the query
    count without adding real comparison diversity. The caller fills any
    shortfall from the triple family instead, which has a much larger
    combinatorial space."""
    weight = dict(pool)
    labels = [lbl for lbl, _ in pool]
    pairs = [(a, b) for a, b in itertools.combinations(labels, 2)
             if frozenset((a, b)) not in ancestor_pairs]
    entries = []
    for i, (a, b) in enumerate(pairs):
        if len(entries) >= target_count:
            break
        tmpl = PAIRWISE_TEMPLATES[i % len(PAIRWISE_TEMPLATES)]
        text = tmpl.format(a=a, b=b)
        wa, wb = weight[a], weight[b]
        gap = abs(wa - wb)
        correct = a if wa > wb else b
        wrong = b if wa > wb else a
        gt = {"mode": "pairwise", "correct": [correct], "wrong": [wrong],
              "near_tie": gap < NEAR_TIE_THRESHOLD, "gap": round(gap, 1)}
        entries.append({"id": f"pairwise_{len(entries)+1}", "text": text, "family": "pairwise", "ground_truth": gt})
    return entries


def _triple_entries(pool, ancestor_pairs, target_count):
    weight = dict(pool)
    labels = [lbl for lbl, _ in pool]
    triples_all = [(a, b, c) for a, b, c in itertools.combinations(labels, 3)
                   if not (frozenset((a, b)) in ancestor_pairs
                           or frozenset((a, c)) in ancestor_pairs
                           or frozenset((b, c)) in ancestor_pairs)]
    # Stride-sample evenly across the full (weight-sorted-pool-order) combination
    # list rather than taking it sequentially from the front: pool is built
    # domain-by-domain in weight-descending order, so the first N combinations
    # would almost all contain the single highest-weight label, making nearly
    # every triple's "correct" answer identical - a real diversity problem
    # found by inspecting the first generated batch. A stride spreads triples
    # across the whole space so different labels end up "correct" across the set.
    stride = max(1, len(triples_all) // max(1, target_count))
    candidates = triples_all[::stride]
    entries = []
    for i, (a, b, c) in enumerate(candidates):
        if len(entries) >= target_count:
            break
        tmpl = TRIPLE_TEMPLATES[i % len(TRIPLE_TEMPLATES)]
        text = tmpl.format(a=a, b=b, c=c)
        ranked = sorted([a, b, c], key=lambda lbl: -weight[lbl])
        top_gap = weight[ranked[0]] - weight[ranked[1]]
        gt = {"mode": "triple", "correct": [ranked[0]], "wrong": ranked[1:],
              "near_tie": top_gap < NEAR_TIE_THRESHOLD, "gap": round(top_gap, 1)}
        entries.append({"id": f"triple_{len(entries)+1}", "text": text, "family": "triple", "ground_truth": gt})
    return entries


def generate(graph_data, top_path_labels, target_total=100, n_pairwise_cap=70):
    """Fills GENERIC (fixed 20) first, then PAIRWISE up to n_pairwise_cap or
    however many distinct valid pairs exist (whichever is smaller - see
    _pairwise_entries), then fills any remaining budget up to target_total
    from TRIPLE, which has a much larger combinatorial space and so can
    always make up a graph-size-dependent shortfall without repeating an
    underlying comparison."""
    pool = _pool(graph_data)
    ancestor_pairs = _ancestor_pairs(graph_data)
    generics = _generic_entries(graph_data, top_path_labels)
    pairwise = _pairwise_entries(pool, ancestor_pairs, n_pairwise_cap)
    n_triple = target_total - len(generics) - len(pairwise)
    triple = _triple_entries(pool, ancestor_pairs, n_triple)
    return generics + pairwise + triple


if __name__ == "__main__":
    g1 = generate(DEMO_GRAPH, TOP_PATH_LABELS)
    g2 = generate(DEMO_GRAPH_2, TOP_PATH_LABELS_2)

    out1 = os.path.join(HERE, "queries_n100_graph1.json")
    out2 = os.path.join(HERE, "queries_n100_graph2.json")
    with open(out1, "w") as f:
        json.dump(g1, f, indent=2)
    with open(out2, "w") as f:
        json.dump(g2, f, indent=2)

    for name, entries in [("graph1", g1), ("graph2", g2)]:
        n_generic = sum(1 for e in entries if e["family"] == "generic")
        n_pairwise = sum(1 for e in entries if e["family"] == "pairwise")
        n_triple = sum(1 for e in entries if e["family"] == "triple")
        n_ambiguous = sum(1 for e in entries if e["ground_truth"]["mode"] == "ambiguous")
        n_near_tie = sum(1 for e in entries if e["ground_truth"].get("near_tie"))
        print(f"{name}: {len(entries)} total | generic={n_generic} pairwise={n_pairwise} "
              f"triple={n_triple} | ambiguous={n_ambiguous} near_tie_excluded={n_near_tie}")

    print(f"\nWrote {out1} and {out2}")
